name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }} / Agda ${{ matrix.agda }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        ghc: ["8.10.7"]
        node: ["14"]
        cabal: ["3.6"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cabal freeze
        run: |
          cabal v2-update
          cabal v2-freeze -finstall-agda --enable-tests --enable-benchmarks

      - name: Add Cabal installdir to path (Unix)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        id: cabal-installdir
        run: |
          echo "${HOME}/.cabal/bin" >> $GITHUB_PATH
          echo '::set-output name=cabal-installdir::${HOME}/.cabal/bin'
        shell: bash

      - name: Add Cabal installdir to path (Windows)
        if: runner.os == 'Windows'
        id: cabal-installdir
        run: |
          echo "$env:APPDATA\cabal\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo '::set-output name=cabal-installdir::$env:APPDATA\cabal\bin'
        shell: powershell

      - name: Cache ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            ${{ steps.cabal-installdir.outputs.cabal-installdir }}
            dist-newstyle
          key: ${{ matrix.os }}-GHC-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.os }}-GHC-${{ matrix.ghc }}-

      - name: Build website
        run: make build

      - name: Test website
        run: make test
